PAPER_RESULTS = {
    "dataset_stats": [
        {"month": "June", "date": "2024-06-01", "total_patches": 2630, "flooded_percent": 41.8},
        {"month": "July", "date": "2024-07-01", "total_patches": 2249, "flooded_percent": 13.3},
        {"month": "August", "date": "2024-08-01", "total_patches": 1889, "flooded_percent": 3.9},
    ],
    "model_metrics": [
        {"rank": 1, "model": "XGBoost", "roc_auc": 0.3681, "accuracy": "6.9%", "precision": "3.2%", "recall": "100.0%", "f1": 0.0629, "training_time_s": 481.3, "result_status": "REAL_UNOSAT_VALIDATION", "note": "NDWI-free model scored on 1,024 real Copernicus Sentinel patches against UNOSAT FL20240825BGD labels."},
        {"rank": 2, "model": "Simple CNN", "roc_auc": 0.9982, "accuracy": "99.0%", "precision": "82.9%", "recall": "93.2%", "f1": 0.877, "result_status": "SIMULATED_NOT_PUBLISHABLE"},
        {"rank": 3, "model": "Logistic Regression", "roc_auc": 0.9978, "accuracy": "99.2%", "precision": "85.2%", "recall": "94.5%", "f1": 0.896, "result_status": "SIMULATED_NOT_PUBLISHABLE"},
        {"rank": 4, "model": "Random Forest", "roc_auc": 0.9976, "accuracy": "99.1%", "precision": "84.1%", "recall": "94.5%", "f1": 0.890, "result_status": "SIMULATED_NOT_PUBLISHABLE"},
        {"rank": 5, "model": "SVM (RBF)", "roc_auc": 0.9908, "accuracy": "97.7%", "precision": "65.0%", "recall": "89.0%", "f1": 0.751, "result_status": "SIMULATED_NOT_PUBLISHABLE"},
        {"rank": 6, "model": "ResNet-18", "roc_auc": 0.9848, "accuracy": "95.9%", "precision": "48.5%", "recall": "87.7%", "f1": 0.624, "result_status": "SIMULATED_NOT_PUBLISHABLE"},
    ],
    "ablation_results": [
        {"configuration": "UNOSAT_MARGIN_0.000", "features": 45, "roc_auc": 0.3681, "accuracy": 0.0693, "precision": 0.0325, "recall": 1.0000, "f1": 0.0629, "time_s": 481.28, "result_status": "REAL_UNOSAT_VALIDATION"},
        {"configuration": "UNOSAT_MARGIN_0.125", "features": 45, "roc_auc": 0.3851, "accuracy": 0.1133, "precision": 0.0782, "recall": 1.0000, "f1": 0.1450, "time_s": 481.28, "result_status": "REAL_UNOSAT_VALIDATION"},
        {"configuration": "UNOSAT_MARGIN_0.250", "features": 45, "roc_auc": 0.4196, "accuracy": 0.1289, "precision": 0.0944, "recall": 1.0000, "f1": 0.1725, "time_s": 481.28, "result_status": "REAL_UNOSAT_VALIDATION"},
        {"configuration": "UNOSAT_MARGIN_0.375", "features": 45, "roc_auc": 0.4191, "accuracy": 0.1357, "precision": 0.1015, "recall": 1.0000, "f1": 0.1843, "time_s": 481.28, "result_status": "REAL_UNOSAT_VALIDATION"},
        {"configuration": "UNOSAT_MARGIN_0.500", "features": 45, "roc_auc": 0.4617, "accuracy": 0.1270, "precision": 0.0924, "recall": 1.0000, "f1": 0.1691, "time_s": 481.28, "result_status": "REAL_UNOSAT_VALIDATION"},
    ],
    "confusion_matrices": [
        {"model": "XGBoost", "test_patches": 1024, "missed_floods": 0, "false_positives": 953, "true_positives": 32, "true_negatives": 39, "result_status": "REAL_UNOSAT_VALIDATION"},
    ],
    "metric_audit": [
        {
            "item": "SVM (RBF) ROC-AUC",
            "table_a1_value": 0.9908,
            "resolved_value": 0.9908,
            "status": "verified_against_seeded_table",
            "note": "The app now treats the structured Table A1 value as the displayed value for SVM unless a full-paper source is supplied.",
        },
        {
            "item": "ResNet-18 ROC-AUC",
            "table_a1_value": 0.9848,
            "resolved_value": 0.9848,
            "status": "verified_against_seeded_table",
            "note": "The app now treats the structured Table A1 value as the displayed value for ResNet-18 unless a full-paper source is supplied.",
        },
        {
            "item": "Section 4.2.1 cross-check",
            "status": "source_missing_from_local_pdf",
            "note": "The bundled PDF is a four-page progress report and does not contain Section 4.2.1 or Table A1 text, so the inconsistency is documented instead of silently reconciled from unavailable prose.",
        },
    ],
    "independent_validation": {
        "evidence_tiers": [
            {"tier": "Ground truth", "source": "UNOSAT/Copernicus EMS flood maps", "role": "Validation labels only"},
            {"tier": "Model signal", "source": "Sentinel-derived patch features and XGBoost probabilities", "role": "Flood classification score"},
            {"tier": "Operational forecast", "source": "Open-Meteo rainfall, soil moisture, and discharge", "role": "Forecast context only"},
        ],
        "source": {
            "name": "UNOSAT FL20240825BGD",
            "product_id": "3954",
            "title": "Satellite detected water extents between 28 August & 4 September 2024 in Bangladesh",
            "source_url": "https://unosat.org/products/3954",
            "shapefile_url": "https://unosat.org/static/unosat_filesystem/3954/FL20240825BGD_SHP.zip",
            "event_code": "FL20240825BGD",
            "sensor": "Sentinel-1",
            "acquisition_window": "2024-08-18 to 2024-09-04",
            "published": "2024-09-08",
            "reported_flooded_area_km2": 8100,
            "reported_receded_area_km2": 8700,
            "reported_exposed_population": 6200000,
            "caveat": "Preliminary satellite analysis; not field validated. Radar flood analysis can underestimate water in built-up or densely vegetated areas.",
        },
        "ground_truth": {
            "patches": 1024,
            "flooded_patches": 32,
            "flooded_percent": 3.12,
            "grid": "32x32 patch-centroid labels over the UNOSAT analysed extent",
        },
        "metric_status": "computed",
        "metric_note": "Metrics compare real Copernicus Sentinel patch scores against UNOSAT flood-extent labels. NDWI water fraction is reported as a validation score, not used as a label, and the XGBoost classifier uses 45 non-NDWI features.",
        "score_artifact": "backend/validation/bangladesh_2024_real_scores.csv",
        "first_principles_note": "The system is optimized around independent evidence: labels come from external flood maps, model probabilities come from Sentinel features, and forecast context is kept separate from validation.",
        "patch_audit_artifact": "backend/validation/audits/bangladesh_2024/patch_level_audit.csv",
        "summary_artifact": "backend/validation/unosat_bangladesh_2024_summary.json",
        "failure_analysis_artifact": "backend/validation/audits/bangladesh_2024/failure_analysis.md",
        "buffer_ablation_artifact": "backend/validation/audits/bangladesh_2024/buffer_ablation.csv",
        "ndwi_threshold_metrics": {
            "patches": 1024,
            "roc_auc": 0.4232,
            "accuracy": 0.8008,
            "precision": 0.0114,
            "recall": 0.0625,
            "f1": 0.0192,
            "confusion_matrix": {"tn": 818, "fp": 174, "fn": 30, "tp": 2},
        },
        "model_probability_metrics": {
            "patches": 1024,
            "roc_auc": 0.3681,
            "accuracy": 0.0693,
            "precision": 0.0325,
            "recall": 1.0,
            "f1": 0.0629,
            "confusion_matrix": {"tn": 39, "fp": 953, "fn": 0, "tp": 32},
        },
        "failure_case_summary": {
            "false_positives": 953,
            "false_negatives": 0,
            "true_positives": 32,
            "true_negatives": 39,
            "note": "The model over-predicts flood at the default 0.5 threshold. Built-up and dense-vegetation radar limitations are plausible hypotheses from the UNOSAT caveat, but land-cover attribution still needs a separate land-cover layer.",
        },
        "operational_fallback_audit": {
            "metric_status": "computed_stratified_sample",
            "sample": "64 UNOSAT grid patches: 32 flooded and 32 non-flooded controls, evaluated on 2024-09-04 with the unauthenticated Open-Meteo fallback.",
            "model_probability_metrics": {
                "patches": 64,
                "roc_auc": 0.5791,
                "accuracy": 0.5,
                "precision": 0.0,
                "recall": 0.0,
                "f1": 0.0,
                "confusion_matrix": {"tn": 32, "fp": 0, "fn": 32, "tp": 0},
            },
            "verdict": "The fallback is not a validated flood classifier and should be treated as a conservative triage proxy until real Sentinel patch scores are supplied.",
        },
    },
    "modularity_evidence": [
        "The backend /regions endpoint seeds 27 flood-prone countries across Asia, Africa, Europe, Oceania, and the Americas.",
        "The predictor accepts arbitrary country, latitude, longitude, and date inputs rather than a Dhaka-only route contract.",
        "The satellite fetcher builds a bounding box from any lat/lon and buffer size, then falls back to Open-Meteo proxy arrays when Copernicus credentials or scenes are unavailable.",
    ],
    "methodology_references": [
        {
            "key": "tang_2023_forecasting_pattern_recognition",
            "title": "Flood forecasting based on machine learning pattern recognition and dynamic migration of parameters",
            "authors": "Yehai Tang, Yue Sun, Zhenyue Han, Shan-e-hyder Soomro, Qiang Wu, Boyu Tan, and Caihong Hu",
            "year": 2023,
            "venue": "Journal of Hydrology: Regional Studies, 47, 101406",
            "doi": "10.1016/j.ejrh.2023.101406",
            "citation": "Tang, Y., Sun, Y., Han, Z., Soomro, S.-e.-h., Wu, Q., Tan, B., & Hu, C. (2023). Flood forecasting based on machine learning pattern recognition and dynamic migration of parameters. Journal of Hydrology: Regional Studies, 47, 101406. https://doi.org/10.1016/j.ejrh.2023.101406",
            "relevance": "Used as methodology guidance for rainfall-pattern classification, probability-weighted forecast thinking, and uncertainty-aware dashboard communication; this app does not implement the paper's Xin'anjiang hydrological parameter-migration model.",
        }
    ],
    "sensitivity_analysis": {
        "ndwi_threshold": "Real UNOSAT validation at NDWI water-fraction threshold 0.05: ROC-AUC 0.4232, F1 0.0192.",
        "label_margin": "Real UNOSAT margin ablation improved model F1 from 0.0629 at margin 0.0 to 0.1843 at margin 0.375, but precision remained low.",
        "patch_size": "Current real validation uses the 32x32 UNOSAT audit grid with Sentinel patches read at 64x64 pixels.",
    },
    "key_features": [
        {"rank": 1, "feature": "VV/B04/NDVI engineered statistics", "description": "The current XGBoost model excludes NDWI-derived features from its input vector."},
        {"rank": 2, "feature": "NDWI water fraction", "description": "Reported only as an audited validation score against UNOSAT, not used as a model input."},
    ],
    "paper_notes": [
        "Study area: central Bangladesh using a 50 km buffer around Dhaka.",
        "Table A1 and Table 3 are treated as authoritative where prose conflicts with structured values, with SVM and ResNet-18 AUC values now explicitly audited.",
        "NDWI-derived water fraction is no longer used as an XGBoost model input in the validation pass; independent validation labels come from UNOSAT FL20240825BGD.",
        "The modularity claim is supported by global region seeding and arbitrary country/lat/lon prediction inputs.",
        "Open-Meteo forecasting is an operational extension, not a paper result.",
    ],
}
